services:
    # Admin class to provide editor configurations to JS frontend
    # This service is common to both Sulu 2.x and 3.0
    Akawaka\SuluMultiCKEditorBundle\Admin\MultiEditorAdmin:
        arguments:
            - '@parameter_bag'
        tags:
            - { name: sulu.admin }
